[pelican]
author = "Grant Paton-Simpson"
sitename = "SofaLite - SOFA Statistics the Python Library"
timezone  = "Pacific/Auckland"
default_lang = "en"

[publish]
site_url = "https://sofalite.github.io"
